### ISSUE TITLE
Modal signup/login widget is unescapable

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/whatgotdone#406]
Normally, modal login pop-up widgets are closable when the user clicks outside of the pop-up widget. At [3:00](https://youtu.be/JnAAkjS4x6k?t=180) in the video, DK notices that What Got Done's widget remains open and modal even when the user clicks outside the widget.

I believe this is actually a bug in [UserKit's](https://userkit.io) hosted widget, so I'll follow up with them.

Note that this is related to [The /login route breaks the back button (#405)](https://github.com/mtlynch/whatgotdone/issues/405), but they're two separate issues.

**Comment by dtq** [comment]
I believe the issue is that the login-dismiss flag is set to false:
https://github.com/mtlynch/whatgotdone/blob/05fb09accf33cb44cbb8d669596293a1ba6dedf2/frontend/src/controllers/UserKit.js#L45

Deleting that line should fix this.

My guess is that this flag was copied over from our UserKit quick-start docs, we should probably add clarification in the docs (or a code comment) to make it clearer what that flag does.

**Comment by mtlynch** [comment]
Thanks @dtq! I was holding off on bothering you guys until the end of the weekend, but that fixed it. Thanks!
