### ISSUE TITLE
Feature: Add Starter Template

### ISSUE THREAD

**Issue by czue** [mtlynch/whatgotdone#468]
Most of my entries take the form:

```
## [Some Project](www.example.com/1)

- thing 1
- thing 2

## [Another Project](www.example.com/2)

- thing 1
- thing 2
```

I'd be nice if I could have a "starter template" associated with my account that was the base for all new entries (similar to how github pull request templates work).

(this is a very minor annoyance, but figured I'd report it)

**Comment by mtlynch** [comment]
This is something I've been craving as well.

My workaround has been to visit week n - 1's update, edit it, copy it, then paste it into a new update. But twice now, I've accidentally edited the wrong week in that process and wiped out my previous week. Last time, I recovered the update from the [daily backup](https://github.com/mtlynch/whatgotdone/tree/master/backup-service), but this time, I realized that the daily backup has been [broken since January](https://github.com/mtlynch/whatgotdone/pull/460).

One thing I've been considering was was to offer an option to auto-generate the boilerplate based on the last 3-4 entries, but I'll just think about the tradeoffs aloud:

### A. Manually entered template

* Pros
  * Simple to implement and reason about
  * Recognizable to people who are familiar with things like Github's issue or PR templates.
* Cons
  * Doesn't work well if your projects vary frequently

### B. Automatically inferred template

* Pros
  * User has to perform less configuration, feels like What Got Done magically understands them
* Cons
  * It will only work for update structures we recognize
  * Harder to implement

I think I should just go with (A)

**Comment by czue** [comment]
Wow, thanks for the quick response! The "edit" workflow is a good workaround for now. Agree that manual templates are a better plan than trying to do magic to generate them.

**Comment by czue** [comment]
Just took this for a spin - looks great. Thanks for the super fast turnaround!

**Comment by mtlynch** [comment]
Yeah, I'm enjoying it more than I expected, too. Thanks for the suggestion!
